[package]
name = "rust-graphql-example"
version = "0.1.0"
authors = ["Ian Wilson <iwilsonq@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "4.1.0"
actix-cors = "0.6.2"
actix-rt = "2.7.0"
juniper_actix = "0.4.0"
diesel = { version = "2.0.0", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.24"
juniper = "0.15.10"
serde = { version = "1.0.144", features = ["derive"] }
serde_derive = "1.0.144"
serde_json = "1.0.85"
