install:
	cargo install sea-orm-cli


set_db_url:
	echo postgres://lunchspider:archi@localhost:10000/autodoxgraphql > .env

init:
	sea-orm-cli migrate init


migrate:
	diesel migration generate create_members

run:
	cargo run

kill:
	kill -INT $(lsof -t -i :8080)