install:
	cargo install sea-orm-cli


set_db_url:
	echo postgres://lunchspider:archi@localhost:10000/autodoxgraphql > .env

init:
	sea-orm-cli migrate init




run:
	cargo run

kill:
	kill -INT $(lsof -t -i :8080)

run_celery_beats:
	cargo run beat_app




migrate:
	sea-orm-cli migrate generate posts


run:
	cargo run
#
#migrate:
#	diesel migration generate create_members